language:
  - node_js
  - python

python:
    - "2.7"

node_js:
  - "0.10"
  - "4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

services: redis-server

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user `whoami` virtualenv

script: make travis

after_script:
  - npm run outdated
  - npm run audit-shrinkwrap

notifications:
  irc:
    channels:
      - "irc.mozilla.org#loop"
    use_notice: false
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message} %{build_url}"
